### ISSUE TITLE
Drop Python 3.2 support for CI?

### ISSUE THREAD

**Issue by hartwork** [fschulze/pytest-flakes#14]
Hi!

I noticed that:
* pytest [is using `u"..."` syntax](https://travis-ci.org/fschulze/pytest-flakes/jobs/193677012) that was dropped in Python 3.x and re-introduced with 3.3 only; that made CI fail for #12
* pytest [does not officially support Python 3.2](https://pypi.python.org/pypi/pytest)
* pytest-flakes uses Python 3.2 with tox: `envlist = py25,py26,py27,py32,py33,py34,py35`

I think Python 3.2 support needs to be dropped?

**Comment by hartwork** [comment]
That was fast, thanks!

For the record, related commit is ce60d7e520ad8a49c17c27f470f6318c3e4a1768.

**Comment by hartwork** [comment]
pypy3 seems to be using Python 3.2 still? See `pip 8.1.2 from /home/travis/virtualenv/pypy3-2.4.0/site-packages (python 3.2)` at https://travis-ci.org/fschulze/pytest-flakes/jobs/231547347 .

**Comment by fschulze** [comment]
I run but ignore the pypy3 tests on travis now.

**Comment by hartwork** [comment]
aa1bb562944a3122aebadcc4ea19a5116eb0bfd3

Have you considered [using `pypy3.3-5.2-alpha1` instead of `pypy3`](https://github.com/jwilk/anorack/commit/435f0f00fe4678e9675e56c344f1368ed1515acb) for Travis?
May need `dist: trusty` as well, not sure

**Comment by fschulze** [comment]
Thanks for the tip!
