### ISSUE TITLE
Use pyflakes' isPythonFile instead of checking for .py

### ISSUE THREAD

**Issue by asmeurer** [fschulze/pytest-flakes#16]
pyflakes itself has support for files that don't end in .py but have a Python shebang line. The function it uses is part of the api ([`isPythonFile`](https://github.com/PyCQA/pyflakes/blob/d2af071c84344de2aa633c1f314ef6cfe6c9515f/pyflakes/api.py#L115)). This should use that.

**Comment by fschulze** [comment]
I'd be happy to merge a PR if you are able to make one.
